-- https://leetcode.com/problems/students-and-examinations/description/

-- Write your MySQL query statement below
SELECT 
    STU.STUDENT_ID,
    STU.STUDENT_NAME,
    SUB.SUBJECT_NAME,
    COUNT(EXA.SUBJECT_NAME) AS ATTENDED_EXAMS
FROM STUDENTS STU
JOIN
SUBJECTS SUB
LEFT JOIN
EXAMINATIONS EXA
ON STU.STUDENT_ID=EXA.STUDENT_ID
AND SUB.SUBJECT_NAME=EXA.SUBJECT_NAME
GROUP BY 1,2,3
ORDER BY 1,2
